"""empty message

Revision ID: ba6afd233d72
Revises: 
Create Date: 2018-04-05 13:00:34.487879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba6afd233d72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('team', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId')
    )
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentId', sa.Integer(), nullable=True),
    sa.Column('day1', sa.Integer(), nullable=True),
    sa.Column('day2', sa.Integer(), nullable=True),
    sa.Column('day3', sa.Integer(), nullable=True),
    sa.Column('day4', sa.Integer(), nullable=True),
    sa.Column('day5', sa.Integer(), nullable=True),
    sa.Column('day6', sa.Integer(), nullable=True),
    sa.Column('day7', sa.Integer(), nullable=True),
    sa.Column('day8', sa.Integer(), nullable=True),
    sa.Column('day9', sa.Integer(), nullable=True),
    sa.Column('day10', sa.Integer(), nullable=True),
    sa.Column('day11', sa.Integer(), nullable=True),
    sa.Column('day12', sa.Integer(), nullable=True),
    sa.Column('day13', sa.Integer(), nullable=True),
    sa.Column('day14', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['studentId'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data')
    op.drop_table('users')
    # ### end Alembic commands ###
